name: CI

on:
  push:
    branches: [ master, test ]
#  pull_request:
#    branches: [ master, test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
        
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: dir "$GITHUB_WORKSPACE"
        
